import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: Platform.OS === 'android' ? 40 : 60,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#666',
    includeFontPadding: false,
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 10,
    includeFontPadding: false,
  },
  subHeader: {
    fontSize: 16,
    color: '#555',
    marginBottom: 25,
    lineHeight: 22,
    includeFontPadding: false,
  },
  highlight: {
    color: '#4A9F8F',
    fontWeight: '600',
  },
  scoreCard: {
    backgroundColor: '#E8F5E9',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    marginBottom: 30,
    // Android Elevation
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  scoreLabel: {
    fontSize: 14,
    color: '#4A9F8F',
    fontWeight: '600',
    marginBottom: 5,
    includeFontPadding: false,
  },
  scoreValue: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 5,
    includeFontPadding: false,
  },
  scoreDesc: {
    fontSize: 14,
    color: '#555',
    textAlign: 'center',
    includeFontPadding: false,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 15,
    includeFontPadding: false,
  },
  roleCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#EEE',
    // Android Elevation for card depth
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  roleTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 6,
    includeFontPadding: false,
  },
  roleDesc: {
    fontSize: 14,
    color: '#666',
    marginBottom: 12,
    includeFontPadding: false,
  },
  matchBadge: {
    alignSelf: 'flex-end',
    backgroundColor: '#4A9F8F',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  matchText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
    includeFontPadding: false,
  },
  retryButton: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#4A9F8F',
    paddingVertical: 14,
    borderRadius: 25,
    alignItems: 'center',
    marginTop: 10,
    elevation: 2,
  },
  retryText: {
    color: '#4A9F8F',
    fontSize: 16,
    fontWeight: '600',
    includeFontPadding: false,
  },
});